CFLAGS = $(GLOBALFLAGS)

L = $(EW_HOME)/$(EW_VERSION)/lib

LIB = libcrypto

OBJS = \
	memxor.o \
	hmac-sha1.o \
	sha1.o

$L/$(LIB).a: $L/$(LIB).a($(OBJS))


# Clean-up rules
clean: PHONY
	-$(RM) a.out core *.o *.obj *% *~
	-$(RM) $L/$(LIB).a $L/$(LIB).lib $L/$(LIB).dll

PHONY:
