!IF "$(EW_DEBUG)" == "1"
!ELSE
NODEBUG = 1
!ENDIF

!include <Win32.Mak>

CFLAGS  = $(cflags)    $(cdebug) $(cvarsmt)   $(GLOBALFLAGS)

L = $(EW_HOME)\$(EW_VERSION)\lib

LIB = libdali

OBJS = \
	config.obj \
	connection.obj \
	genutils.obj \
	logging.obj \
	network.obj \
	parse_ip_address.obj \
	portable.obj \
	statefile.obj \
	strutils.obj \
	timeutils.obj

all: $L\$(LIB).lib

$L\$(LIB).lib: $(OBJS)
	lib /nologo /out:$@ $(OBJS)

$L\$(DLL).dll: $(OBJS)
	$(link) /dll /nologo /out:$@ $(OBJS)


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~
	-del $L\$(LIB).a $L\$(LIB).lib $L\$(LIB).dll

PHONY:
