#
# Dummy makefile - only used for cleaning things up
#

default: FAIL


# Clean-up rules
clean: PHONY
	-del a.out core *.o *.obj *% *~
	-del qlib2.h qlib2.inc qlib2_90.inc
	-del /q lib\* lib64\*

PHONY:
