#pragma once
/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed May 22 18:13:24 2002
 */
#ifndef __CEXTRACT__
#if defined(__STDC__) || defined(_WIN32)

extern void apply(float *, int, int);
extern void design(int, char *, char *, float, float, float, float, float);
extern int grgmin ( int *, int * );
extern int mingrg ( int *, int * );
extern void UWDFcarry_sec ( struct stime * );
extern int UWDFchbias ( int );
extern char *UWDFchcompflg ( int );
extern char UWDFchfmt ( int );
extern char *UWDFchid ( int );
extern int UWDFchlen ( int );
extern struct sta_loc UWDFchloc ( int );
extern int UWDFchlta ( int );
extern char *UWDFchname ( int );
extern int UWDFchno ( char *, char *, char * );
extern int UWDFchref_stime ( int, struct stime * );
extern int UWDFchret_trace ( int, char, void * );
extern int UWDFchclipped(void);
extern int LlnlFilterClear( void );
extern int LlnlFilterDesign( int, char *, char *, float, float, float, float, int );
extern char *LlnlFilterPrint( void );
extern int LlnlFilterApply( float *, int, float, void *, char );
extern int UWDFchret_filtered_trace(int , char, void *);
extern float UWDFchsrate ( int );
extern char *UWDFchsrc ( int );
extern int UWDFchtrig ( int );
extern int UWDFch_is_rev ( int );
extern int UWDFclose_file ( void );
extern int UWDFclose_new_file ( void );
extern int UWDFconv_to_doy ( int, int, int, int * );
extern int UWDFconv_to_mon_day ( int, int, int *, int * );
extern float UWDFcoord_dist ( struct sta_loc, struct sta_loc );
extern int UWDFdelete_new_file ( void );
extern char *UWDFdhcomment ( void );
extern int UWDFdhevno ( void );
extern char *UWDFdhext ( void );
extern short *UWDFdhflgs ( void );
extern int UWDFdhfmt_type_for_read ( void );
extern int UWDFdhnchan ( void );
extern int UWDFdhref_stime ( struct stime * );
extern int UWDFdhtapeno ( void );
extern float UWDFdist_az ( struct sta_loc, struct sta_loc, float *, float * );
extern int UWDFdup_chead_into_proto ( int );
extern int UWDFdup_masthead ( void );
extern struct sta_loc *UWDFget_sta_loc ( char * );
extern int UWDFinit_for_new_write ( char * );
extern int UWDFinit_rev_table ( char *, int );
extern int UWDFinit_sta_table ( char * );
extern int UWDFis_uw2 ( void );
extern int UWDFmax_trace_len ( void );
extern int UWDFopen_file ( char * );
extern struct chhead2 *UWDFret_chead_proto_struct ( void );
extern struct chhead2 *UWDFret_chead_struct ( int );
extern struct masthead *UWDFret_mast_struct ( void );
extern struct masthead *UWDFret_new_mhead_struct ( void );
extern int UWDFset_chbias ( int );
extern int UWDFset_chcompflg ( char * );
extern int UWDFset_chid ( char [] );
extern int UWDFset_chlta ( int );
extern int UWDFset_chname ( char * );
extern int UWDFset_chref_stime ( struct stime );
extern int UWDFset_chsrate ( float );
extern BOOL UWDFset_chsrc ( char * );
extern int UWDFset_chtrig ( int );
extern int UWDFset_dhcomment ( char * );
extern int UWDFset_dhevno ( short int );
extern int UWDFset_dhextra ( char [] );
extern int UWDFset_dhflgs ( short int [] );
extern int UWDFset_dhref_stime ( struct stime );
extern int UWDFset_dhtapeno ( short int );
extern int UWDFsta_mapping_on ( char * );
extern char* UWDFmapped_sta(char *old_name);
extern char* UWDFmapped_chan(char *old_name);
extern char* UWDFmapped_id(char *old_name);
extern char* UWDFmapped_src(char *old_name);
extern float UWDFtime_diff ( struct stime, struct stime );
extern void UWDFwrite_ieee_byte_order(void);
extern void UWDFwrite_intel_byte_order(void);
extern void UWDFwrite_dec_byte_order(void);
extern void UWDFwrite_host_byte_order(void);
extern int UWDFwrite_new_chan ( char, int, void *, char );
extern int UWDFwrite_new_head ( void );
#if defined(USBR) && ! defined(_WIN32)
extern BOOL DFgetname ( char *, gid_t );
extern int DFopen ( char *, gid_t, int * );
#else
extern BOOL DFgetname ( char * );
extern int DFopen ( char *, int, int * );
#endif
extern char *DFmakename ( struct stime, char * );
extern void DFrmOld ( char *, int );
extern BOOL DFstd_uw_name ( char * );
extern float stot_ch ( int, int );
extern float stot_m ( int, int );
extern int ttos_ch ( int, float );
extern int ttos_m ( int, float );

#else /* __STDC__ */

extern int grgmin (/* int *, int * */);
extern int mingrg (/* int *, int * */);
extern void UWDFcarry_sec (/* struct stime * */);
extern int UWDFchbias (/* int */);
extern char *UWDFchcompflg (/* int */);
extern char UWDFchfmt (/* int */);
extern char *UWDFchid (/* int */);
extern int UWDFchlen (/* int */);
extern struct sta_loc UWDFchloc (/* int */);
extern int UWDFchlta (/* int */);
extern char *UWDFchname (/* int */);
extern int UWDFchno (/* char *, char *, char * */);
extern int UWDFchref_stime (/* int, struct stime * */);
extern int UWDFchret_trace (/* int, char, void * */);
extern float UWDFchsrate (/* int */);
extern char *UWDFchsrc (/* int */);
extern int UWDFchtrig (/* int */);
extern int UWDFch_is_rev (/* int */);
extern int UWDFclose_file (/* void */);
extern int UWDFclose_new_file (/* void */);
extern int UWDFconv_to_doy (/* int, int, int, int * */);
extern int UWDFconv_to_mon_day (/* int, int, int *, int * */);
extern float UWDFcoord_dist (/* struct sta_loc, struct sta_loc */);
extern int UWDFdelete_new_file (/* void */);
extern char *UWDFdhcomment (/* void */);
extern int UWDFdhevno (/* void */);
extern char *UWDFdhext (/* void */);
extern short *UWDFdhflgs (/* void */);
extern int UWDFdhfmt_type_for_read (/* void */);
extern int UWDFdhnchan (/* void */);
extern int UWDFdhref_stime (/* struct stime * */);
extern int UWDFdhtapeno (/* void */);
extern float UWDFdist_az (/* struct sta_loc, struct sta_loc, float *, float * */);
extern int UWDFdup_chead_into_proto (/* int */);
extern int UWDFdup_masthead (/* void */);
extern struct sta_loc *UWDFget_sta_loc (/* char * */);
extern int UWDFinit_for_new_write (/* char * */);
extern int UWDFinit_rev_table (/* char *, int */);
extern int UWDFinit_sta_table (/* char * */);
extern int UWDFis_uw2 (/* void */);
extern int UWDFmax_trace_len (/* void */);
extern int UWDFopen_file (/* char * */);
extern struct chhead2 *UWDFret_chead_proto_struct (/* void */);
extern struct chhead2 *UWDFret_chead_struct (/* int */);
extern struct masthead *UWDFret_mast_struct (/* void */);
extern struct masthead *UWDFret_new_mhead_struct (/* void */);
extern int UWDFset_chbias (/* int */);
extern int UWDFset_chcompflg (/* char * */);
extern int UWDFset_chid (/* char [] */);
extern int UWDFset_chlta (/* int */);
extern int UWDFset_chname (/* char * */);
extern int UWDFset_chref_stime (/* struct stime */);
extern int UWDFset_chsrate (/* float */);
extern BOOL UWDFset_chsrc (/* char * */);
extern int UWDFset_chtrig (/* int */);
extern int UWDFset_dhcomment (/* char * */);
extern int UWDFset_dhevno (/* short int */);
extern int UWDFset_dhextra (/* char [] */);
extern int UWDFset_dhflgs (/* short int [] */);
extern int UWDFset_dhref_stime (/* struct stime */);
extern int UWDFset_dhtapeno (/* short int */);
extern int UWDFsta_mapping_on (/* char * */);
extern float UWDFtime_diff (/* struct stime, struct stime */);
extern int UWDFwrite_new_chan (/* char, int, void *, char */);
extern int UWDFwrite_new_head (/* void */);
extern BOOL DFgetname (/* char *, gid_t */);
extern char *DFmakename (/* struct stime, char * */);
extern int DFopen (/* char *, gid_t, int * */);
extern void DFrmOld (/* char *, int */);
extern BOOL DFstd_uw_name (/* char * */);
extern float stot_ch (/* int, int */);
extern float stot_m (/* int, int */);
extern int ttos_ch (/* int, float */);
extern int ttos_m (/* int, float */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
